binance:
  api_key: "${BINANCE_API_KEY}"
  api_secret: "${BINANCE_API_SECRET}"
  futures_env: "testnet" # "testnet" or "real"

telegram:
  bot_token: "7743046161:AAG1P4Yo6lZZ7t1Auo10Aeyp8YFdkvL5KNw"
  chat_id: "1131830593"

trading:
  symbol: "BTCUSDT"
  trade_amount: 0.01 # in BTC
  risk_percentage: 0.01 # not used yet, but kept
  timeframe: "5m"
  take_profit: 1.5 # in % (for info / strategy)
  stop_loss: 1.0 # in % (for info / strategy)
  break_even_enabled: true
  break_even_trigger_pct: 0.4
  position_file: "position_btc.json"

timing:
  price_interval_seconds: 5
  indicator_interval_seconds: 300
  loop_interval: 5 # seconds between decision checks

database:
  url: "postgresql://postgres:vRbMZvLpoWdNwYMJceMpYssawyUDCKen@hopper.proxy.rlwy.net:40569/railway"

